### ISSUE TITLE
False claim as spam account

### ISSUE THREAD

**Issue by ArnoCan** [pypa/.github#2]
See also #536:
I am a bit astoinished about this story!

So as a long term contributor working on a large framework for which I am going to deploy the first parts it is irritating to be called a spammer or if this obviously not fits a troll, or whatever.

That is bullying - as I guess here in order to actually troll the name datafusion see #659.

So please assure that this thing stops immediatley.

WKR

**Comment by xavfernandez** [comment]
Hello, this seems like a duplicate of https://github.com/pypa/pypi-support/issues/702.
Let's keep the discussion there.

If you want to raise a CoC issue, please use the provided email.
